version: '3.5'  

services:
  frontend: 
    build: ./frontend 
    ports: 
      - 5000:5000
    command: npm start
  backend: 
    build: ./backend
    volumes: 
        - ./logs.txt:/app/logs.txt
    ports: 
      - 8000:8000
    environment:
      - REDIS=cache
    command: npm start
  cache:
    image: redis
    restart: unless-stopped
  