version: '3.5'  

services:
  backend: 
    build: ./backend
    volumes: 
        - ./backend/logs.txt:/usr/app/logs.txt
    ports: 
      - 8000:8000
    environment:
      - FRONT_URL=http://127.0.0.1:5000
    command: npm start
  frontend: 
    build: ./frontend 
    ports: 
      - 5000:5000
    environment:
      - API_URL=http://127.0.0.1:8000
    command: npm start